services:
  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      timeout: 10s
      interval: 30s
      retries: 3

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/stats-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10